### ISSUE TITLE
Using app_page_url in template for non-wagtail_app_pages page

### ISSUE THREAD

**Issue by drcongo** [mwesterhof/wagtail_app_pages#2]
* Wagtail App Pages version: 0.2.3
* Wagtail version: 2.0.1
* Django version: 2.0.6
* Python version: 3.6.3
* Operating System: Alpine Linux

### Description

I'm trying to use `app_page_url` in a template on a standard Wagtail page, but looking at the template tags code it looks like it's only usable on another app_page or the child of an app_page?

### What I Did

This code, in the template for standard Wagtail pages...
```
<li class="tag"><a href="{{ app_page_url('tag_index_page_view_base', slug=tag.slug) }}">{{ tag.name }}</a></li>
```

This throws a template rendering error `'ArticlePage' object has no attribute 'reverse'`, which of course is true.

Is `wagtail_app_pages` an all or nothing thing, where I need to add the AppPageMixin to all of my page types?

**Comment by drcongo** [comment]
(I should mention that I'm working around it for now by adding an instance of the AppPage to the context of every other page and passing this to `app_page_url` as a kwarg `app_page`, this feels like a dirty hack though)

```<li class="tag"><a href="{{ app_page_url('tag_index_page_view_base', app_page=tag_app_page, slug=tag.slug) }}">{{ tag.name }}</a></li>```

**Comment by mwesterhof** [comment]
Thanks for reporting the issue. Unfortunately, this isn't a bug, exactly (as mentioned in the docs). 
In principle, there's nothing stopping someone who wants to make multiple instances of your app page (in case of a multi-language solution like wagtailtrans, this will actually be very likely), and because of that, I can't make any assumptions about what your "default" instance of the page will be. So, in order to do a reverse lookup, we will absolutely *need* to know the actual instance. The app_page_url tag will automatically figure that out if you use it from a template within the app itself, but this won't work outside of it. There are a few ways to deal with this. Ill give some examples based on this:

Let's say i have a wagtail project that includes 2 types of app pages:
* A news app, which is used to present news articles
* A products app, which shows a catalogue of products
We want to allow multiple instances of the products app, each with different cms-able content, and maybe even some custom settings, exposed to admin users (a regular version, discounted products, highlighted, landing page version etc). 
News articles will be used to promote the products, so we should be able to link to them from the news app. The system will actually need to know which version of the products app to use though.

Here are a few proposed ways to deal with this:

* Every news app page (you could have more than one) should know which products page to use, so why not explicitly link them together? in this case, the news app page would just have a foreignkey to make this possible. Then, the linked page could simply be passed to the template tag.
* Maybe it makes more sense to say that a site has a "default products page". In that case, it could actually be turned into a site setting. That way, it would work pretty transparantly in a multi-site setting
* If your specific case makes it really easy to "guess" what the right instance is (the only/first instance of the page model, or if there's a specific filter that can be used to fetch it), you could consider rolling your own templatetag to fix it. In this case, that would be a templatetag, written to specifically reverse "products" urls. If you have a valid app_page instance, you can just do an app_page.reverse() call from python. If your case is that simple, Making a templatetag to wrap this up nicely is probably the cleanest way to fix it

Sorry for the long-winded reply. Unfortunately, your question hits on something fundamental about this approach to url routing. Please let me know if this wasn't clear enough, I'd be happy to elaborate or discuss other proposed solutions. I'll probably explain this in more detail in the docs as well.

**Comment by drcongo** [comment]
That's very clear, thank you for such a comprehensive reply. I think a custom template tag for our routes is probably the way to go. Thanks again.

**Comment by mwesterhof** [comment]
updated the docs to better describe this point (https://wagtail-app-pages.readthedocs.io/en/latest/caveats.html#lack-of-determinism)
